module.exports = {
    hlds: {
        server_name: 'Fake HLDS by kalle',
        server_players: '15',
        server_maxplayers: '24',
        bots: '2',
        server_description: 'Hidden',
        map: 'de_dust2',
        appid: '10', // halflife
        protocol: '48',
        // First is selected
        type: [
            'd', // dedicated
            //'l', // nondedicated
            //'p'  // hltv
        ],
        // First is selected
        os: [
            'l', // linux
            //'w', // win  
            //'o'  // mac
        ],
        password: 0,
        vac: 1,
        version: '1.1.2.7/Stdio',
        players: [
            {
                nickname: 'player 1',
                frags: 10,
                seconds: 50
            },
            {
                nickname: 'player 2',
                frags: 20,
                seconds: 80
            },
            {
                nickname: 'player 3',
                frags: 30,
                seconds: 180
            }
        ],

        rules: {
            "afk_manager_version":	"1.0.6 (amx 1.8.3)",
            "allow_spectators":	"0",
            "amxmodx_version":	"1.10.0.5417",
            "amx_client_languages":	"1",
            "amx_contactinfo":	"github.com/kallefrombosnia",
            "amx_default_advert":	"github.com/kallefrombosnia",
            "amx_language":	"en",
            "amx_new_advert":	"[E.K]-Pla[y]er",
            "coop":	"0",
            "CRXChatManager":	"4.8",
            "CRXFastKnife":	"1.0.1",
            "CRXRankSystem": "3.10",
            "deathmatch": "1",
            "decalfrequency": "60",
            "dedicated": "100",
            "edgefriction": "2",
            "ff_damage_reduction_bullets": "0.35",
            "ff_damage_reduction_grenade": "0.25",
            "ff_damage_reduction_grenade_self": "1.0",
            "ff_damage_reduction_other": "0.35",
            "game_description": "Counter-Strike",
            "game_directory": "cstrike",
            "game_version": "5.20.0.505-dev",
            "humans_join_team": "any",
            "max_queries_sec": "1",
            "max_queries_sec_global": "1",
            "max_queries_window": "1",
            "mdbBans": "4.8",
            "metamod_version": "1.3.0.128",
            "mp_afk_bomb_drop_time": "0",
            "mp_autokick": "0",
            "mp_autokick_timeout": "-1",
            "mp_autoteambalance": "2",
            "mp_buytime": "0.25",
            "mp_buy_anywhere": "0",
            "mp_c4timer": "35",
            "mp_chattime": "5",
            "mp_consistency": "1",
            "mp_fadetoblack": "0",
            "mp_falldamage": "0",
            "mp_flashlight": "0",
            "mp_footsteps": "1",
            "mp_forcecamera": "0",
            "mp_forcechasecam": "0",
            "mp_forcerespawn": "0",
            "mp_fraglimit": "0",
            "mp_fragsleft": "0",
            "mp_freeforall": "0",
            "mp_freezetime": "0",
            "mp_friendlyfire": "0",
            "mp_give_player_c4": "1",
            "mp_hostagepenalty": "0",
            "mp_hostage_hurtable": "1",
            "mp_infinite_ammo": "0",
            "mp_infinite_grenades": "0",
            "mp_item_staytime": "300",
            "mp_kickpercent": "0.66",
            "mp_limitteams": "0",
            "mp_logdetail": "0",
            "mp_logfile": "1",
            "mp_logmessages": "0",
            "mp_mapvoteratio": "0.66",
            "mp_maxmoney": "16000",
            "mp_maxrounds": "0",
            "mp_playerid": "0",
            "mp_radio_maxinround": "60",
            "mp_radio_timeout": "1.5",
            "mp_respawn_immunitytime": "0",
            "mp_respawn_immunity_effects": "1",
            "mp_respawn_immunity_force_unset": "1",
            "mp_roundover": "0",
            "mp_roundtime": "1.75",
            "mp_round_infinite": "0",
            "mp_round_restart_delay": "5",
            "mp_scoreboard_showdefkit": "1",
            "mp_scoreboard_showhealth": "3",
            "mp_scoreboard_showmoney": "3",
            "mp_show_scenarioicon": "0",
            "mp_startmoney": "850",
            "mp_timeleft": "0",
            "mp_timelimit": "0",
            "mp_tkpunish": "0",
            "mp_weapons_allow_map_placed": "1",
            "mp_windifference": "1",
            "mp_winlimit": "0",
            "OS": "108",
            "pausable": "0",
            "pingfake_flux": "4",
            "pingfake_ping": "12",
            "protocol_version": "48",
            "reaimdetector_version": "0.2.2",
            "reauthcheck_version": "0.1.6",
            "reply_format": "source",
            "resemiclip_version": "2.3.9",
            "resrdetector_version": "0.1.0",
            "reu_version": "0.1.0.137",
            "SNAC_Version": "1.1",
            "steamAppId": "10",
            "suggested_bot_count": "0",
            "suggested_players": "32",
            "sv_accelerate": "5",
            "sv_aim": "0",
            "sv_airaccelerate": "100",
            "sv_allowupload": "0",
            "sv_alltalk": "1",
            "sv_bounce": "1",
            "sv_cheats": "0",
            "sv_clienttrace": "1",
            "sv_contact": "github.com/kallefrombosnia",
            "sv_friction": "4",
            "sv_gravity": "1",
            "sv_logblocks": "0",
            "sv_maxRate": "100000",
            "sv_maxspeed": "900",
            "sv_minrate": "70000",
            "sv_password": "0",
            "sv_proxies": "0",
            "sv_restart": "0",
            "sv_restartround": "0",
            "sv_stepsize": "18",
            "sv_stopspeed": "75",
            "sv_uploadmax": "0.5",
            "sv_version": "1.1.2.7/Stdio,48,2537",
            "sv_voiceenable": "0",
            "sv_wateraccelerate": "10",
            "sv_waterfriction": "1",
            "version": "1.1.2.7/Stdio",
            "whb_version": "1.5.696",
        }
    }
}